# Generated by Django 3.2.9 on 2021-11-22 16:15

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topico_swebook_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Tópico 1')),
            ],
        ),
        migrations.CreateModel(
            name='Topico_swebook_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Tópico 2')),
                ('associacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.topico_swebook_1')),
            ],
        ),
        migrations.AddField(
            model_name='exemplo',
            name='conhecimento_previo_ou_restricoes',
            field=models.TextField(verbose_name='Conhecimento Prévio e Restrições de Uso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exemplo',
            name='exemplo_descicao_conceitual_problema',
            field=models.TextField(verbose_name='Descrição Conceitual do Problema'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exemplo',
            name='exemplo_descricao_solucao',
            field=models.TextField(verbose_name='Descrição da Solução e Etapas da Solução'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exemplo',
            name='exemplo_imagem_problema',
            field=stdimage.models.StdImageField(upload_to='IMG-exemplos', verbose_name='Imagem para demonstrar o contexto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exemplo',
            name='exemplo_imagem_resultado',
            field=stdimage.models.StdImageField(upload_to='IMG-exemplos', verbose_name='Imagem para demonstrar um resultado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exemplo',
            name='exemplo_imagem_solucao',
            field=stdimage.models.StdImageField(upload_to='IMG-exemplos', verbose_name='Imagem para demonstrar as etapas de solução'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exemplo',
            name='exemplo_material_complementar',
            field=models.TextField(verbose_name='Material Complementar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exemplo',
            name='exemplo_ocorrencia_problema',
            field=models.TextField(verbose_name='Ocorrência do Problema no Projeto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exemplo',
            name='exemplo_resultado',
            field=models.TextField(verbose_name='Resultado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exemplo',
            name='outros_topicos',
            field=models.CharField(max_length=200, verbose_name='Outros Tópicos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exemplo',
            name='projeto_data_extracao_exemplo',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exemplo',
            name='projeto_descricao',
            field=models.TextField(verbose_name='Descrição do Projeto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exemplo',
            name='projeto_linguagem_programacao',
            field=models.CharField(max_length=200, verbose_name='Linguagem de Programação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exemplo',
            name='projeto_link',
            field=models.CharField(max_length=200, verbose_name='Link do Projeto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exemplo',
            name='projeto_link_exemplo',
            field=models.CharField(max_length=200, verbose_name='Link do Exemplo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exemplo',
            name='projeto_nome',
            field=models.CharField(max_length=200, verbose_name='Nome do projeto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exemplo',
            name='sugestores_de_uso',
            field=models.TextField(verbose_name='Sugestões de Uso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exemplo',
            name='tag_1',
            field=models.CharField(max_length=200, verbose_name='Tag 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exemplo',
            name='tag_2',
            field=models.CharField(max_length=200, verbose_name='Tag 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exemplo',
            name='tag_3',
            field=models.CharField(max_length=200, verbose_name='Tag 3'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Topico_swebook_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Tópico 3')),
                ('associacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.topico_swebook_2')),
            ],
        ),
        migrations.AddField(
            model_name='exemplo',
            name='topico_swebook_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.topico_swebook_1'),
        ),
        migrations.AddField(
            model_name='exemplo',
            name='topico_swebook_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.topico_swebook_2'),
        ),
        migrations.AddField(
            model_name='exemplo',
            name='topico_swebook_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.topico_swebook_3'),
        ),
    ]
