# Generated by Django 3.2.9 on 2021-11-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211122_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemplo',
            name='outros_topicos',
            field=models.CharField(max_length=200, null=True, verbose_name='Outros Tópicos'),
        ),
    ]
