# Generated by Django 3.2.9 on 2021-11-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_exemplo_outros_topicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemplo',
            name='outros_topicos',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Outros Tópicos'),
        ),
    ]
