# Generated by Django 3.2.9 on 2021-11-22 16:25

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_exemplo_outros_topicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemplo',
            name='conhecimento_previo_ou_restricoes',
            field=models.TextField(blank=True, null=True, verbose_name='Conhecimento Prévio e Restrições de Uso'),
        ),
        migrations.AlterField(
            model_name='exemplo',
            name='exemplo_descicao_conceitual_problema',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição Conceitual do Problema'),
        ),
        migrations.AlterField(
            model_name='exemplo',
            name='exemplo_imagem_problema',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='IMG-exemplos', verbose_name='Imagem para demonstrar o contexto'),
        ),
        migrations.AlterField(
            model_name='exemplo',
            name='exemplo_imagem_resultado',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='IMG-exemplos', verbose_name='Imagem para demonstrar um resultado'),
        ),
        migrations.AlterField(
            model_name='exemplo',
            name='exemplo_imagem_solucao',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='IMG-exemplos', verbose_name='Imagem para demonstrar as etapas de solução'),
        ),
        migrations.AlterField(
            model_name='exemplo',
            name='exemplo_material_complementar',
            field=models.TextField(blank=True, null=True, verbose_name='Material Complementar'),
        ),
        migrations.AlterField(
            model_name='exemplo',
            name='exemplo_ocorrencia_problema',
            field=models.TextField(blank=True, null=True, verbose_name='Ocorrência do Problema no Projeto'),
        ),
        migrations.AlterField(
            model_name='exemplo',
            name='exemplo_resultado',
            field=models.TextField(blank=True, null=True, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='exemplo',
            name='projeto_data_extracao_exemplo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exemplo',
            name='projeto_descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Projeto'),
        ),
        migrations.AlterField(
            model_name='exemplo',
            name='projeto_linguagem_programacao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Linguagem de Programação'),
        ),
        migrations.AlterField(
            model_name='exemplo',
            name='projeto_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Link do Projeto'),
        ),
        migrations.AlterField(
            model_name='exemplo',
            name='projeto_link_exemplo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Link do Exemplo'),
        ),
        migrations.AlterField(
            model_name='exemplo',
            name='projeto_nome',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do projeto'),
        ),
        migrations.AlterField(
            model_name='exemplo',
            name='sugestores_de_uso',
            field=models.TextField(blank=True, null=True, verbose_name='Sugestões de Uso'),
        ),
        migrations.AlterField(
            model_name='exemplo',
            name='tag_1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tag 1'),
        ),
        migrations.AlterField(
            model_name='exemplo',
            name='tag_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tag 2'),
        ),
        migrations.AlterField(
            model_name='exemplo',
            name='tag_3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tag 3'),
        ),
    ]
