# Generated by Django 3.2.9 on 2021-11-22 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_avaliacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
    ]
