# Generated by Django 3.2.9 on 2021-11-23 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_alter_avaliacao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topico_swebook_1',
            options={'verbose_name': 'Tópico SWEBOOK 1', 'verbose_name_plural': 'Tópicos SWEBOOK 1'},
        ),
        migrations.AlterModelOptions(
            name='topico_swebook_2',
            options={'verbose_name': 'Tópico SWEBOOK 2', 'verbose_name_plural': 'Tópicos SWEBOOK 2'},
        ),
        migrations.AlterModelOptions(
            name='topico_swebook_3',
            options={'verbose_name': 'Tópico SWEBOOK 3', 'verbose_name_plural': 'Tópicos SWEBOOK 3'},
        ),
        migrations.AddField(
            model_name='exemplo',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
